version: "3"
services:
  kafka:
    image: spotify/kafka
  producer:
    build:
      context: producer/
    ports:
      - 8080:8080
    depends_on:
      - kafka
    environment:
      kafka.host: kafka
      kafka.port: 9092
  consumer:
    build:
      context: consumer/
    depends_on:
      - kafka
    environment:
      kafka.host: kafka
      kafka.port: 9092
